<a href="https://colab.research.google.com/github/chirag-star/Python_Practicals_Sem5/blob/main/Practical_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Printing version and configuration of numpy
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
import numpy as np
# Creating a numpy array
Array = np.array([1, 2, 3, 4, 5, 6, 7])
print(Array)
print(type(Array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
# Creating an array with 10 zeros,10 ones, 10 fives
array = np.zeros(10)
print(array)
array = np.ones(10)
print(array)
array = np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
import numpy as np
# Generating random number between 0 and 1
Random = np.random.rand(5,5)
print(Random)

[[0.95693635 0.92118584 0.4333402  0.29746954 0.82309108]
 [0.3900937  0.9348158  0.49727795 0.39897008 0.23410021]
 [0.05188392 0.6049615  0.61112229 0.94417377 0.99443717]
 [0.90306387 0.05782006 0.85942235 0.22707801 0.7524793 ]
 [0.31879732 0.5049396  0.50159758 0.41381636 0.14762097]]
